image: node:8-alpine

stages:
  - test
  - build
  - publish

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm pack
  artifacts:
    paths:
      - foris-*.tgz

publish_beta:
  stage: publish
  only:
    refs:
      - dev
  script:
    - sh scripts/publish.sh beta

publish_latest:
  stage: publish
  only:
    refs:
      - master
  script:
    - sh scripts/publish.sh latest
